// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as mods$0 from "../../../../Enigamitsuj/among-us-mod-launcher/internal/mods/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "install:progress": mods$0.InstallProgress;
        }
    }
}
