// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Launcher is the Wails-bound service the frontend talks to.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mods$0 from "../mods/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(55242247);
}

export function DestinationExists(modID: string, amongUsPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(4194768515, modID, amongUsPath);
}

export function DetectGame(): $CancellablePromise<mods$0.GameStatus> {
    return $Call.ByID(1360421780);
}

export function GetDefaultMod(): $CancellablePromise<mods$0.Mod> {
    return $Call.ByID(555649552);
}

export function GetInstallState(modID: string, amongUsPath: string): $CancellablePromise<mods$0.InstallState> {
    return $Call.ByID(731559087, modID, amongUsPath);
}

export function GetMods(): $CancellablePromise<mods$0.Mod[] | null> {
    return $Call.ByID(400700654);
}

export function GetReleases(modID: string): $CancellablePromise<mods$0.Release[] | null> {
    return $Call.ByID(3610493921, modID);
}

/**
 * Install starts a background install and emits "install:progress" events.
 */
export function Install(opts: mods$0.InstallOptions): $CancellablePromise<void> {
    return $Call.ByID(1672524380, opts);
}

export function IsGameRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(3300111362);
}

export function LaunchMod(installPath: string): $CancellablePromise<void> {
    return $Call.ByID(886002982, installPath);
}

export function MinimizeWindow(): $CancellablePromise<void> {
    return $Call.ByID(2556216769);
}

/**
 * SetWindow stores the main window handle for minimize/close.
 */
export function SetWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(1835761935, w);
}

export function Uninstall(modID: string, amongUsPath: string): $CancellablePromise<void> {
    return $Call.ByID(3505174981, modID, amongUsPath);
}
