// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameInstall is one detected Among Us copy (mirrors game.Install for bindings).
 */
export interface GameInstall {
    "platform": string;
    "path": string;
    "version": string;
    "buildId": string;
    "branch": string;
    "supported": boolean;
    "canInstall": boolean;
    "assetHint": string;
    "message": string;
    "launchHint": string;
}

/**
 * GameStatus describes the detected Among Us install(s).
 */
export interface GameStatus {
    "found": boolean;
    "path": string;
    "version": string;
    "platform": string;
    "platformLabel": string;
    "buildId": string;
    "branch": string;
    "supported": boolean;
    "canInstall": boolean;
    "running": boolean;
    "assetHint": string;
    "steamFound": boolean;
    "steamPath": string;
    "epicFound": boolean;
    "itchFound": boolean;
    "xboxFound": boolean;
    "message": string;
    "installs": GameInstall[] | null;
}

/**
 * InstallOptions are user choices for an install run.
 */
export interface InstallOptions {
    "modId": string;
    "versionTag": string;
    "amongUsPath": string;
    "platform": string;
    "forceReinstall": boolean;
}

/**
 * InstallProgress is emitted during installation.
 */
export interface InstallProgress {
    "stage": string;
    "message": string;
    "percent": number;
    "done": boolean;
    "error": string;
    "installDir": string;
}

/**
 * InstallState describes whether a mod is already installed.
 */
export interface InstallState {
    "installed": boolean;
    "path": string;
    "version": string;
    "exists": boolean;
    "managed": boolean;
}

/**
 * Mod describes a community mod the launcher can install.
 */
export interface Mod {
    "id": string;
    "name": string;
    "shortName": string;
    "description": string;
    "author": string;
    "githubOwner": string;
    "githubRepo": string;
    "folderName": string;
    "accentFrom": string;
    "accentTo": string;
    "enabled": boolean;
    "comingSoon": boolean;

    /**
     * RequiredGameVersion is the Among Us version this mod targets (e.g. "17.3").
     */
    "requiredGameVersion": string;

    /**
     * RecommendedTags are curated release tags known to be stable.
     */
    "recommendedTags": string[] | null;
}

/**
 * Release is a simplified GitHub release shown in the UI.
 */
export interface Release {
    "tagName": string;
    "name": string;
    "body": string;
    "publishedAt": string;
    "prerelease": boolean;
    "downloadUrl": string;
    "downloadName": string;
    "downloadSize": number;
    "htmlUrl": string;
    "assetMatched": boolean;
    "assetHint": string;

    /**
     * Compatibility of this release against the currently detected game.
     */
    "compatLevel": string;
    "compatReason": string;
    "installable": boolean;
    "recommended": boolean;
}
