// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GameStatus describes the detected Among Us install.
 */
export interface GameStatus {
    "found": boolean;
    "path": string;
    "version": string;
    "supported": boolean;
    "running": boolean;
    "steamFound": boolean;
    "steamPath": string;
    "message": string;
}

/**
 * InstallOptions are user choices for an install run.
 */
export interface InstallOptions {
    "modId": string;
    "versionTag": string;
    "amongUsPath": string;
    "installLocation": string;
    "createShortcut": boolean;
    "launchAfterInstall": boolean;
    "forceReinstall": boolean;
}

/**
 * InstallProgress is emitted during installation.
 */
export interface InstallProgress {
    "stage": string;
    "message": string;
    "percent": number;
    "done": boolean;
    "error": string;
    "installDir": string;
}

/**
 * InstallState describes whether a mod is already installed.
 */
export interface InstallState {
    "installed": boolean;
    "path": string;
    "version": string;
    "exists": boolean;
}

/**
 * Mod describes a community mod the launcher can install.
 */
export interface Mod {
    "id": string;
    "name": string;
    "shortName": string;
    "description": string;
    "author": string;
    "githubOwner": string;
    "githubRepo": string;
    "folderName": string;
    "accentFrom": string;
    "accentTo": string;
    "enabled": boolean;
    "comingSoon": boolean;
}

/**
 * Release is a simplified GitHub release shown in the UI.
 */
export interface Release {
    "tagName": string;
    "name": string;
    "body": string;
    "publishedAt": string;
    "prerelease": boolean;
    "downloadUrl": string;
    "downloadName": string;
    "downloadSize": number;
    "htmlUrl": string;
}
